### ISSUE TITLE
R version error -- time to bump

### ISSUE THREAD

**Issue by cmatKhan** [nickjer/singularity-r#7]
I appreciate your recipe -- thank you for providing it. This is not really an issue -- I see you've bumped the version in the history previously, so I'm sure this is on the todo list -- and more of a question:

How would you go about building a image with specifically 4.1.3, for instance, if the current version of R is past that? I am guessing that it has to do with this:

```
  add-apt-repository \
    "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
```
But I'm not sure how to get a specific version of R as opposed to the most current.

**Comment by nickjer** [comment]
I currently specify the version of R in two places:

- https://github.com/nickjer/singularity-r/blob/69fdf9fd60d541b122e8710f7a035041d0ce32b9/singularity-r.def#L6
- https://github.com/nickjer/singularity-r/blob/69fdf9fd60d541b122e8710f7a035041d0ce32b9/singularity-r.def#L19

So you would update both of those places. But as you have pointed out the repository is specifically setup for `cran40`, if you wanted an earlier version (< 4.x) you might need to find the corresponding repository.

**Comment by nickjer** [comment]
As an aside I just now bumped it to 4.2.0 with this commit: https://github.com/nickjer/singularity-r/commit/1fd11cbc0dde1eb7bf13a3447bbb4a88dac29bdb

I am currently uploading the image to the Cloud Library.
